### ISSUE TITLE
Virtual Machine

### ISSUE THREAD

**Issue by stefanpoeter** [Beckhoff/CX9020#1]
Do you have a good setup for a virtual machine like bochs or so to test the image on?

**Comment by pbruenn** [comment]
Short answer: no, we don't have a virtual machine setup simulating the CX9020.

To test the bootloader and kernel we have to run it on real hardware.
However, to configure the rootfs we use "chroot + qemu-arm-static (see [scripts/40_install_rootfs.sh](https://github.com/Beckhoff/CX9020/blob/master/scripts/40_install_rootfs.sh) for details).
This might be helpful for you creating custom images.

As a side note: we will soon replace debootstrap with multistrap for the demo rootfs.

**Comment by stefanpoeter** [comment]
Thanks.
