### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by LanderU** [Beckhoff/CX9020#10]
Hello everybody!

I'm trying to deploy the master on **CX9020** device, following the README instructions.
I can create SD card without problems, but, when I start the init.d service, the output shows "done". But, when I check the service status, the output shows "dead". 

Anybody have the same problem?

**Comment by pbruenn** [comment]
if you mean: `/etc/init.d/etherlab start`
I see the same:
```
root@CX9020:~# /etc/init.d/ethercat start
Starting EtherCAT master 1.5.2  done
root@CX9020:~# /etc/init.d/ethercat status
Checking for EtherCAT master 1.5.2
Master0  dead
```
But kernel log looks fine, and running an example application should work, too.
```
root@CX9020:~# dmesg | grep -i cat
[    0.002200] ftrace: allocating 21480 entries in 63 pages
[    0.062745] DMA: preallocated 256 KiB pool for atomic coherent allocations
[   18.667110] EtherCAT: Master driver 1.5.2 a1079c6242a5
[   18.669109] EtherCAT: 1 master waiting for devices.
[   18.715426] ec_ccat: registered ec_ccat as gpiochip503 with #9 GPIOs.
[   18.715488] EtherCAT: Accepting 00:01:05:22:34:A9 as main device for master 0.
[   18.715502] EtherCAT 0: Starting EtherCAT-IDLE thread.
[   18.718773] ec_ccat: ccat_sram_probe: 0x0016 rev: 0x0000
[   18.719066] ec_ccat: registered ccat_sram0.
[   18.722149] EtherCAT 0: Link state of ecm0 changed to UP.
[   18.722161] EtherCAT WARNING 0: 1 datagram UNMATCHED!
[   18.736966] EtherCAT 0: 5 slave(s) responding on main device.
[   18.736984] EtherCAT 0: Slave states on main device: PREOP.
[   18.737215] EtherCAT 0: Scanning bus.
[   19.084961] EtherCAT 0: Bus scanning completed in 340 ms.
[   19.084971] EtherCAT 0: Using slave 0 as DC reference clock.
```
As far as I can read from the init script it looks like the ethercat command line tool is used to determine the master state. But that tool is not include in the CX9020 example rootfs [--disable-tool](https://github.com/Beckhoff/CX9020/blob/master/Makefile#L9). So it would make sense to get a "dead" status, but having a fine master.
If you manage to cross-compile the command line tool. Please, let me know. I'm pretty interested in the result.

**Comment by LanderU** [comment]
Finally I leave the cross compilation way.

I have put all of necessary things inside the image and I'm able to compile natively.

Anyway, thanks for your help!
