### ISSUE TITLE
Sniff the network

### ISSUE THREAD

**Issue by LanderU** [Beckhoff/CX9020#11]
Hi!

I have some troubles to capture the packages between `CX9020` Linux master with etherlab and `ccat` configured.

My configuration:

`CX9020` --> `EK 1110` --> `LAN9252`

I'm able to sniff the EtherCAT packages using, "man on the middle" technique, but the intermediate computer is not real time machine and I have some delays.

Is it possible sniff directly on mater? How?

Thanks in advance!

**Comment by LanderU** [comment]
Also, is this device [CU2508](http://www.beckhoff.co.uk/english.asp?pc_cards_switches/cu2508.htm?id=35911031548), compatible with the Linux master?

**Comment by pbruenn** [comment]
I would use an [ET2000](http://www.beckhoff.com/default.asp?ethercat/et2000.htm) for sniffing
```
CX9020<->EK1110<->ET2000<->LAN9252
                     |
                 PC (Wireshark)
```

Sniffing on the master might be a little tricky, as EtherLab doesn't announce it's devices to the Linux network stack.

In general, you would have much more luck with your questions on the EtherLab mailing list. They are much more experienced with EtherLab and EtherCAT on Linux. And they have an answer to the CU2508 compatibility:
http://lists.etherlab.org/pipermail/etherlab-users/2015/002727.html

If you have further questions, feel free to ask. If it is related to EtherLab, try to post on their mailing list. I read that, too, and will respond, if I have an answer:
http://lists.etherlab.org/mailman/listinfo/etherlab-users

**Comment by LanderU** [comment]
@pbruenn, many thanks for your help!
