### ISSUE TITLE
Accessing local I/O modules

### ISSUE THREAD

**Issue by jake-edgenaut** [Beckhoff/CX9020#15]
Hi, I was wondering how one is supposed to access local I/O modules programmatically. I'm new to Beckhoff products in general...from what I gather I need EtherLab, specifically PdServ and PdCom in order to access I/O values from my userspace application, is this correct?

I'm assuming that optional interfaces, such as RS485, just show up as ordinary serial ports e.g. /dev/ttySomething

I apologize for posting a non-issue on here -- I contacted Beckhoff USA tech support first and they gave me a very firm "You cannot use our software with Linux" and "we do not support Linux".

Any help would be appreciated, thank you.

**Comment by pbruenn** [comment]
Hi,
You are right, you can use EtherLab to access local EtherCAT IO terminals. Once you setup the sdcard as described in this repository, you should be able to use EtherLab just as described in their documentation. The EtherLab source already has basic examples to get started. Look at the EtherLab mailing list for additional help, there are quit some very helpful and responsive people. My EtherLab knowledge is quite limited to get a very basic setup running. If you have trouble to compile for the latest kernel, let me know. Patching EtherLab to run on latest mainline/rt kernel is usually straightforward

**Comment by pbruenn** [comment]
Oh and for the additional interfaces, yes they should work out of the box. If they don’t contact us here on GitHub.

**Comment by jake-edgenaut** [comment]
Perfect, thanks Patrick!
