### ISSUE TITLE
Ethernet port X001 doesn't detect link up anymore

### ISSUE THREAD

**Issue by TMesot** [Beckhoff/CX9020#22]
Hello, 
It seems since a certain time, the kernel patch to sense link up on KSZ886X ports [0002-net-phy-multiplex-switch-phy-ports.patch](https://github.com/Beckhoff/CX9020/blob/master/kernel-patches/0002-net-phy-multiplex-switch-phy-ports.patch) doesn't fully work any more. 

If you build the last image ([c66aa23](https://github.com/Beckhoff/CX9020/commit/c66aa234d5b5cb6d1617f0409e5a182c4a9198b7)) with kernel 4.19, connect ethernet port X001, boot the device, then link goes up. If you "soft" reboot (with `reboot` command) the device, the link never came up again. If you power it off and on, link come back but only after "initial" boot.

This doesn't seems affect the X000 port.

I didn't try to git bisect, but at least on kernel 4.4.x it was working.  

Are you aware of something like this ? Do you have an idea what could have changes and create this inconstant behavior ?

Thanks

**Comment by pbruenn** [comment]
Did you set https://github.com/Beckhoff/CX9020/blob/master/kernel-patches/0002-net-phy-multiplex-switch-phy-ports.patch#L45

**Comment by TMesot** [comment]
It's a good question. 
Actually it was set by the `50_install_kernel.sh` script (https://github.com/Beckhoff/CX9020/blob/master/scripts/50_install_kernel.sh) during build to `libphy.num_phys=2` which shows as : 
```
root@CX9020:~# cat /proc/cmdline
console=ttymxc1,115200 libphy.num_phys=2 console=tty0 quiet root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait fixrtc
```

The patch mentioned `phy_driver.num_phys=2`, so I tried to add it or to replace `libphy` with `phy_driver`. 
- With both (`phy_driver.num_phys=2` and `libphy.num_phys=2` ) : same behavior then initial issue. 
- With only `phy_driver.num_phys=2` and with none of the two : 
  - On X000, it works always.
  - On X001, even after "hard" reboot, the port link never goes up (even if led came up)

According to the module name (libphy) [Makefile](https://github.com/torvalds/linux/blob/v4.19/drivers/net/phy/Makefile) and behavior without any declaration, I would say the correct declaration would be (`libphy.num_phys`). 

I've also added some debug log and the loop is correctly process. The only difference between both ports is : https://github.com/Beckhoff/CX9020/blob/master/kernel-patches/0002-net-phy-multiplex-switch-phy-ports.patch#L52. If we are on X0000, we exit due to `phydev->link` been true (1). `ret` value is always 0, which in case of usage of port 2 will hit https://github.com/Beckhoff/CX9020/blob/master/kernel-patches/0002-net-phy-multiplex-switch-phy-ports.patch#L56

Cleaned log when on port X0001
```
[    4.247507] DEBUG: Passed genphy_soft_reset_multiplexed 1714 
[    4.247659] num_phys = 2
[    4.247664] calling genphy_soft_reset for 1
[    4.347920] got ret for call of genphy_soft_reset : 0
[    4.347933] calling genphy_soft_reset for 2
[    4.447953] got ret for call of genphy_soft_reset : 0
[    4.448247] Generic PHY 63fec000.ethernet-1:01: attached PHY driver [Generic PHY] (mii_bus:phy_addr=63fec000.ethernet-1:01, irq=POLL)
[    5.527756] DEBUG: Passed genphy_read_status_multiplexed 1673 
[    5.527888] num_phys = 2
[    5.527893] calling genphy_read_status for 1
[    5.528035] got ret for call of genphy_read_status : 0
[    5.528040] calling genphy_read_status for 2
[    5.528164] got ret for call of genphy_read_status : 0
[    5.528168] returned 0
[    6.567740] DEBUG: Passed genphy_read_status_multiplexed 1673 
[    6.567862] num_phys = 2
[    6.567866] calling genphy_read_status for 1
[    6.568003] got ret for call of genphy_read_status : 0
[    6.568008] calling genphy_read_status for 2
[    6.568132] got ret for call of genphy_read_status : 0
[    6.568135] returned 0
....
```

Cleaned log when on port X0000
```
[    4.293841] DEBUG: Passed genphy_soft_reset_multiplexed 1714 
[    4.293991] num_phys = 2
[    4.293996] calling genphy_soft_reset for 1
[    4.387943] got ret for call of genphy_soft_reset : 0
[    4.387957] calling genphy_soft_reset for 2
[    4.487982] got ret for call of genphy_soft_reset : 0
[    4.488305] Generic PHY 63fec000.ethernet-1:01: attached PHY driver [Generic PHY] (mii_bus:phy_addr=63fec000.ethernet-1:01, irq=POLL)
[    5.527814] DEBUG: Passed genphy_read_status_multiplexed 1673 
[    5.527947] num_phys = 2
[    5.527952] calling genphy_read_status for 1
[    5.528090] got ret for call of genphy_read_status : 0
[    5.528095] calling genphy_read_status for 2
[    5.528217] got ret for call of genphy_read_status : 0
[    5.528630] fec 63fec000.ethernet lan1: Link is Up - 100Mbps/Full - flow control rx/tx
[    6.567822] DEBUG: Passed genphy_read_status_multiplexed 1673 
[    6.567954] num_phys = 2
```

**Comment by TMesot** [comment]
I took some time for a deeper analysis and reach the breaking commit : [5aeaa36b6823dcc743d858de237e3bc5b7d3e1e2](https://github.com/torvalds/linux/commit/5aeaa36b6823dcc743d858de237e3bc5b7d3e1e2). This commit was include in kernel 5.1 and back ported in v4.19.99.

By reverting it, it solve the X001 port staying down after a soft-reboot but failed to auto-negotiate speed if we plug the port while system is already running, which I also investigate and fixed. 

I'll do a PR to offer my solution, which is probably not perfect, but I don't have a clear view of what's going on in KSZ886X and on it's interfaces.
