### ISSUE TITLE
sfdisk on Ubuntu 16.04

### ISSUE THREAD

**Issue by koppi** [Beckhoff/CX9020#3]
Just in case anyone will give a try running the build scripts on Ubuntu 16.04:

sfdisk version 2.26.x or greater lacks the --in-order option (– it is the default as of 2.26.x). You can detect this like so: https://github.com/RobertCNelson/boot-scripts/commit/02f9dc3b2e92c5780acb62e8d97851f334683ec4 .

On Ubuntu 16.04: remove the option from the script. If you want to be sure that partition are in disk order (sorted by start sector) then use command --reorder

  sudo sfdisk --force ${DISK} < ${PARTITION_CONFIG}
  sudo sfdisk --reorder ${DISK}

Note that '--unit M' is also unsupported and --Linux is deprecated and without any effect.

**Comment by pbruenn** [comment]
Thanks for reporting. It took some time but finally commit 3f974cdaf6dcc0f7b1cb850744346533d040ca52 should fix this issue.
Please reopen, if it doesn't.
