### ISSUE TITLE
tools/prepare_kernel.sh does not apply the patch 0004-net-phy-multiplex-switch-phy-ports.patch

### ISSUE THREAD

**Issue by koppi** [Beckhoff/CX9020#4]
Is this intentional?

**Comment by pbruenn** [comment]
Yes, kind of.
That patch tries to hide, that the CX9020 hasn't really two physical Ethernet ports. The internal port is connected to a switch, so the link state is always "up". The patch replaces this static "link up" by a "Link1 up || Link2 up".
As all that is not 100% clean, I don't want to make that behavior the default.

**Comment by pbruenn** [comment]
I changed my mind and since commit bb0ea904708ab1109a53c06e021b7e7b0a9e484f it is applied, too.
